[tool.poetry]
name = "url_shortener"
version = "0.1.0"
description = "URL Shortener application"
authors = ["Sam Ghorbani-40212038 <https://sami-gh05.github.io/personal-portfolio-website/>", "Nima Sayad-40213017"]
readme = "README.md"
package-mode = false

packages = [
  { include = "api" },
]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.1"
sqlalchemy = "^2.0.23"
alembic = "^1.13.1"
psycopg2-binary = "^2.9.9"
fastapi = "^0.115.0"
uvicorn = "^0.30.0"
schedule = "^1.2.2"
httpx = "^0.28.1"
pydantic = "^2.12.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
ruff = "^0.6.9"
black = "^24.8.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main = "api.main:run"
